on:
  release:
    types: [created]

name: Build

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o kubeselect .
      - run: tar czf kubeselect_linux_amd64.tar.gz kubeselect LICENSE README.md
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o kubeselect .
      - run: tar czf kubeselect_darwin_amd64.tar.gz kubeselect LICENSE README.md
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o kubeselect.exe .
      - run: zip kubeselect_windows_amd64.zip kubeselect.exe LICENSE README.md

      - id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Linux asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: kubeselect_linux_amd64.tar.gz
          asset_name: kubeselect_linux_amd64-${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Darwin asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: kubeselect_darwin_amd64.tar.gz
          asset_name: kubeselect_darwin_amd64-${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: kubeselect_windows_amd64.zip
          asset_name: kubeselect_windows_amd64-${{ steps.get_tag_name.outputs.VERSION }}.zip
          asset_content_type: application/zip
